name: 'CI & CD - Staging'

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Generate a GitHub token that can be exchanged with Google Cloud - see
# https://github.com/google-github-actions/auth/tree/v0.6.0#setting-up-workload-identity-federation
permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  testing:
    name: Test Web Application
    runs-on: ubuntu-latest
    container:
      image: ruby:3.0.4
    env:
      POSTGRES_USERNAME_TEST: ${{ secrets.POSTGRES_USERNAME_TEST }}
      POSTGRES_PASSWORD_TEST: ${{ secrets.POSTGRES_PASSWORD_TEST }}
      POSTGRES_DATABASE_URI_TEST: ${{ secrets.POSTGRES_DATABASE_URI_TEST }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Ruby Gems
        run: bundle install

      - name: Runs Specs
        run: rspec spec

  deployment:
    name: Staging Deployment - Google Cloud Platform
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          version: v0.9.1

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: projects/31953380355/locations/global/workloadIdentityPools/ruby-on-rails-gcp-pool/providers/github
          service_account: gh-actions-runner@x-alcove-397919.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.0.0

      - name: Authorize push to Google Cloud Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t us-central1-docker.pkg.dev/x-alcove-397919/rails-gcp-getting-started/rails-gcp-getting-started:staging .



      - name: Push Docker Image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/x-alcove-397919/rails-gcp-getting-started/rails-gcp-getting-started:staging

      - name: Deploy service to Cloud Run
        run: |
          gcloud run deploy staging \
          --image us-central1-docker.pkg.dev/x-alcove-397919/rails-gcp-getting-started/rails-gcp-getting-started:staging \
          --allow-unauthenticated \
          --port 3000 \
          --region us-central1 \
          --min-instances 1 \
          --update-secrets=RAILS_MASTER_KEY=rails-master-key:latest \
          --update-secrets=POSTGRES_USERNAME=db-username-staging:latest \
          --update-secrets=POSTGRES_PASSWORD=db-password-staging:latest \
          --update-secrets=POSTGRES_DATABASE_URI=db-uri-staging:latest
